= Railway

Elixir's `with` doesn't meet my needs. Why is that, and how could it be improved?

== Background

In Elixir, the `with` expression lets us inject pattern-matching guards into a pipeline. Data which does not pattern match "falls out" of the pipeline into the `else` clause, which lets us handle errors:

[source, elixir]
----
v0 = :v0
with(
  {:ok, v1} <- f1(v0),
  {:ok, v2} <- f2(v1)
) do
  happy_path(v2)
else
  :error -> handle_an_error()
end
----

== The Problem

Suppose that `f1` and `f2` may both return an identical error value, e.g. `:error`. We have no choice but to use the same error-handler regardless of whether `f1` or `f2` failed because there is no way to tell which is the case:

[source, elixir]
----
v0 = :v0
with(
  {:ok, v1} <- f1(v0), #=> {:ok, v1} | :error
  {:ok, v2} <- f2(v1)  #=> {:ok, v2} | :error
) do
  happy_path(v2)
else
  # is this from f1 or f2? We can't tell.
  :error -> handle_both_the_same_way()
end
----

Perhaps we can work around this problem. Suppose we define a helper function for `f1` that returns `{:error, :from_f1}` on error, and another for `f2` that returns `{:error, :from_f2}`. This embeds the necessary context into the error value itself, allowing our `else` clause to handle the errors distinctly:

[source, elixir]
----
v0 = :v0
with(
  {:ok, v1} <- f1_helper(v0), #=> {:ok, v1} | {:error, :from_f1}
  {:ok, v2} <- f2_helper(v1)  #=> {:ok, v2} | {:error, :from_f2}
) do
  happy_path(v2)
else
  {:error, :from_f1} -> handle_f1_error()
  {:error, :from_f2} -> handle_f2_error()
end
----

This works, but we would rather not define a helper for every function. For common use-cases like data validation, this becomes tedious; a programmer may need to extract several values from a map, all of which are required, any of which might be missing, each of which should generate a distinct error message for the end-user so that they know what they did wrong.

As another work-around, we could define a "labelling" function that decorates every return value with the context we need:

[source, elixir]
----
label = fn id, value ->
  {id: id, result: value}
end

v0 = :v0
with(
  {id: _, result: {:ok, v1}} <- label(:f1, f1(v0)),  #=> {id: :f1, result: {:ok, v1} | :error}
  {id: _, result: {:ok, v2}} <- label(:f2, f2(v1))   #=> {id: :f2, result: {:ok, v2} | :error}
) do
  happy_path(v2)
else
  {id: :f1, result: _error} -> handle_f1_error()
  {id: :f2, result: _error} -> handle_f2_error()
end
----

As desired, this re-introduces necessary context into the `else` clause, but is no less tedius and cluttered. Perhaps we can do better.

== The Solution

In each of the work-arounds above, we embedded the function's name into the return value of `f1` and `f2` such that our single error-handling `else` block can determine where the error came from and handle it appropriately. Put simply, we identified every error by a function name. However, note that a pipeline is an ordered composition of functions, and therefore we may uniquely identify each function (and consequently any errors it generates) by its position within the composition rather than by its name. With that knowledge, we identify another solution:  We can define multiple error-handlers and embed each into the pipeline at the appropriate position, which lets us recover context based on the order of functions rather than attributes of the data. We have to discard `with` to achieve this, but the result is compelling:

[source, elixir]
----
import Railway
of_one(:v0)
  |> map_ok(f1/1) # f1 :: (:v0 -> {:ok, :v1} | {:error, any})
  |> on_error_return(fn _ -> :e1 end)
  |> map_ok(f2/1) # f2 :: (:v1 -> {:ok, :v2} | {:error, any})
  |> on_error_return(fn _ -> :e2 end)
  |> on_ok_return(fn x -> x end)
  |> eval() #=> evaluates the Railway to :v3, :e1, or :e2
----

Railway is a rudimentary module of _combinators_, relatively simple functions that combine to define a complex pipeline. Railway's combinators abstract over control flow, allowing us to embed short-circuit, context-sensitive error handling into our pipeline exactly as we desire, and without clutter. Here's how it works:

* We create a Railway from an initial value, or "element," using `of_one(:v0)`. We then compose combinators to describe the behavior of the pipeline.
* Once `eval` is invoked, the element flows through each combinator in turn, from top to bottom.
* The element has two states: `ok` and `error`. It begins in the `ok` state and may transition to `error` as combinators act upon it.
* Combinators only apply their callbacks when the element is in the correct state. Above, `map_ok(f1/1)` will only apply `f1` to the element if the element is in the `ok` state. Otherwise, it passes the `error` element along unchanged.
* Some combinators may short-circuit the Railway and immediately return a value. Above, `on_error_return(fn _ -> :e1 end)` is such a combinator, and if it receives an error element, it causes the Railway to evaluate to `:e1` immediately. All the remaining combinators are ignored.

Railway does not represent a new concept, is not intended for production use, and is used only to illustrate the shortcomings of `with` and explain how they may be overcome. The techniques we used to create Railway are similar to those used by reactive programming frameworks like Spring Reactor.
